[project]
name = "plc-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hykyur", email = "caio.lins18@proton.me" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
plc-2026 = "plc_2026:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
